const I0 = {analyte:"Moisture",method:"Gravimetric using vacuum /Hot air oven",reference:"AOAC 934.01"};
const I1 = {analyte:"Protein",method:"Titrimetry by combustion/Kjeldahl/Mixed catalyst",reference:"AOAC 2001.11; Jones (1941)"};
const I2 = {analyte:"Ash",method:"Gravimetric using Muffle furnace",reference:"AOAC 942.05"};
const I3 = {analyte:"Total fat",method:"Gravimetry; Ether extraction using Soxhlet apparatus",reference:"AOAC 963.15"};
const I4 = {analyte:"Total, soluble and insoluble dietary fiber",method:"Enzymatic-gravimetric",reference:"AOAC 991.43"};
const I5 = {analyte:"Available carbohydrate",method:"Calculation by difference",reference:"Greenfield & Southgate (2003)"};
const I6 = {analyte:"Available carbohydrate",method:"Trienzyme extraction and spectrophotometry",reference:"AOAC 991.43; AOAC 985.29"};
const I7 = {analyte:"Energy",method:"Atwater conversion factors",reference:"Merrill & Watt (1973); FAO / INFOODS Guidelines (2012)"};
const I8 = {analyte:"Thiamin",method:"Fluorometry",reference:"AOAC 942.23; Ramasastri (1975)"};
const I9 = {analyte:"Riboflavin",method:"Turbidometric-Microbiological assay",reference:"AOAC 940.33; AOAC 960.46"};
const I10 = {analyte:"Niacin",method:"Turbidometric-Microbiological assay",reference:"AOAC 985.34; 960.46"};
const I11 = {analyte:"Pantothenic acid",method:"RP-HPLC with UV detector",reference:"David & Harvey (2000)"};
const I12 = {analyte:"Vitamin B6",method:"HPLC-fluorometric detection",reference:"AOAC 985.32; Ollilainen (2008)"};
const I13 = {analyte:"Biotin",method:"U-HPLC and LC-ESI-IT-MS method",reference:"Holler et al. (2006)"};
const I14 = {analyte:"Vitamin B9",method:"Trienzyme Extraction and U-HPLC - UV or fluorescence detection",reference:"Finglas et al. (1999); Vahteristo et al. (1996); AOAC 2011.06; AOAC 2013.13"};
const I15 = {analyte:"Vitamin C",method:"RP-HPLC",reference:"AOAC 985.33; Keating & Haddad (1982)"};
const I16 = {analyte:"Vitamin E",method:"HPLC",reference:"AOAC 992.03; AOAC 2012.10"};
const I17 = {analyte:"Vitamin A",method:"HPLC",reference:"AOAC 974.29; Bieri et al. (1979)"};
const I18 = {analyte:"Carotenoids",method:"HPLC",reference:"Delia & Mieko (2004)"};
const I19 = {analyte:"Vitamin D2 & D3",method:"RP- HPLC-APCI-MS.",reference:"AOAC 982.29"};
const I20 = {analyte:"Vitamin K1 & K2",method:"RP- HPLC-APCI-MS",reference:"AOAC 992.27"};
const I21 = {analyte:"Free sugars",method:"HPLC-RID",reference:"AOAC 2013.12"};
const I22 = {analyte:"Starch",method:"Calculated from the increase in the amount of glucose by using conversion factor",reference:"Casterline et al. (1998)"};
const I23 = {analyte:"Oligosaccharides (Raffinose, Stachyose, Verbascose and Ajugose)",method:"HPLC",reference:"Frias et al. (1994); Johansen et al. (1996); Sanchez-Mata et al. (1998)"};
const I24 = {analyte:"Iron, Zinc, Copper, Manganese, Potassium, Magnesium, Sodium, Calcium, Aluminium",method:"Atomic Absorption Spectrophotometry (AAS)",reference:""};
const I25 = {analyte:"Lead, Cadmium, Nickel, Cobalt, Chromium, Lithium, Molybdenum",method:"Graphite furnace Atomic Absorption Spectrophotometry",reference:"AOAC 968.08; AOAC 999.10; AOAC 999.11"};
const I26 = {analyte:"Arsenic, Antimony, Mercury, and Selenium",method:"Atomic Absorption Spectrophotometry (Hydride generation)",reference:""};
const I27 = {analyte:"Phosphorus",method:"Colorimetry",reference:"AOAC 935.45; AOAC 995.11; Fiske & Subbarow (1925)"};
const I28 = {analyte:"Heavy and trace metals Lead, Mercury, Antimony, Cadmium, Molybdenum, Selenium, Arsenic, Cobalt, Nickel, Chromium, Aluminum, Lithium",method:"Inductively Coupled Plasma Mass Spectrometry (ICP-MS)",reference:"AOAC 2013.06"};
const I29 = {analyte:"Citric acid, Malic acid, Fumaric acid, Succinic acid, Lactic acid, Cis-Aconitic acid, Tartaric acid and Quninic acid",method:"HPLC",reference:"AOAC 969.30; AOAC 950.35; AOAC 948.14"};
const I30 = {analyte:"Oxalic acid (Total), Soluble oxalic acid, Insoluble oxalic acid",method:"Fast- HPLC",reference:"Moreau & Savage (2009)"};
const I31 = {analyte:"Fatty acid profile",method:"Gas Chromatography with Flame Ionization Detector",reference:"AOAC 996.06; AOAC 996.01; AOAC 2012.13"};
const I32 = {analyte:"Amino acid profile",method:"Amino acid analyzer (Ion exchange chromatography)",reference:"AOAC 994.12; AOAC 985.28; Landry & Delhaye (1992)"};
const I33 = {analyte:"Stigmasterol, β-Sitosterol, Campesterol, Ergosterol, 5-alpha-Cholestenol",method:"Gas Chromatography (GC)",reference:"AOAC 922.06; Sorenson & Sullivan (2007)"};
const I34 = {analyte:"Polyphenols",method:"HPLC",reference:"Sakakibara et al. (2003)"};
const I35 = {analyte:"Phyates",method:"Ion Exchange and Spectrophotometry",reference:"AOAC 986.11-1988"};
const I36 = {analyte:"Total Saponin",method:"Colorimetry",reference:"Dini et al. (2009)"};
const CORPUS = new Map([
  ["code", null],
  ["name", null],
  ["scie", null],
  ["lang", null],
  ["grup", null],
  ["regn", null],
  ["water", I0],
  ["protcnt", I1],
  ["ash", I2],
  ["fatce", I3],
  ["fibtg", I4],
  ["fibins", I4],
  ["fibsol", I4],
  ["choavldf", I5],
  ["enerc", I7],
  ["thia", I8],
  ["ribf", I9],
  ["nia", I10],
  ["pantac", I11],
  ["vitb6c", I12],
  ["biot", I13],
  ["folsum", I14],
  ["vitc", I15],
  ["retol", I17],
  ["ergcal", I19],
  ["chocal", I19],
  ["doh25", I19],
  ["tocpha", I16],
  ["tocphb", I16],
  ["tocphg", I16],
  ["tocphd", I16],
  ["toctra", I16],
  ["toctrb", I16],
  ["toctrg", I16],
  ["toctrd", I16],
  ["vite", I16],
  ["vitk1", I20],
  ["vitk2", I20],
  ["lutn", I18],
  ["zea", I18],
  ["crypxb", I18],
  ["lycpn", I18],
  ["cartg", I18],
  ["carta", I18],
  ["cartb", I18],
  ["cartoid", I18],
  ["al", I28],
  ["as", I28],
  ["cd", I28],
  ["ca", I24],
  ["cr", I28],
  ["co", I28],
  ["cu", I28],
  ["fe", I28],
  ["pb", I28],
  ["li", I28],
  ["mg", I24],
  ["mn", I28],
  ["hg", I28],
  ["mo", I28],
  ["ni", I28],
  ["p", null],
  ["k", I24],
  ["se", I28],
  ["na", I24],
  ["zn", I24],
  ["cho", I5],
  ["starch", I22],
  ["frus", I21],
  ["glus", I21],
  ["sucs", I21],
  ["mals", I21],
  ["fsugar", I21],
  ["lactose", I21],
  ["f4d0", I31],
  ["f6d0", I31],
  ["f8d0", I31],
  ["f10d0", I31],
  ["f11d0", I31],
  ["f12d0", I31],
  ["f14d0", I31],
  ["f15d0", I31],
  ["f16d0", I31],
  ["f18d0", I31],
  ["f20d0", I31],
  ["f22d0", I31],
  ["f24d0", I31],
  ["f14d1cn5", I31],
  ["f16d1cn7", I31],
  ["f18d1cn9", I31],
  ["f18d1tn9", I31],
  ["f20d1cn9", I31],
  ["f22d1cn9", I31],
  ["f24d1cn9", I31],
  ["f18d2cn6", I31],
  ["f20d2n6", I31],
  ["f22d2n6", I31],
  ["f18d3n3", I31],
  ["f20d3n6", I31],
  ["f20d4n6", I31],
  ["f20d5n3", I31],
  ["f22d5n3", I31],
  ["f22d6n3", I31],
  ["fasat", I31],
  ["fams", I31],
  ["fapu", I31],
  ["cholc", I33],
  ["his", I32],
  ["ile", I32],
  ["leu", I32],
  ["lys", I32],
  ["met", I32],
  ["cys", I32],
  ["phe", I32],
  ["thr", I32],
  ["trp", I32],
  ["val", I32],
  ["ala", I32],
  ["arg", I32],
  ["asp", I32],
  ["glu", I32],
  ["gly", I32],
  ["pro", I32],
  ["ser", I32],
  ["tyr", I32],
  ["oxalt", I30],
  ["oxals", I30],
  ["oxali", I30],
  ["caconac", I29],
  ["citac", I29],
  ["fumac", I29],
  ["malac", I29],
  ["quinac", I29],
  ["sucac", I29],
  ["tarac", I29],
  ["dhbenzac34", I34],
  ["hbenzal3", I34],
  ["pcathac", I34],
  ["vanlac", I34],
  ["gallac", I34],
  ["cinmac", I34],
  ["coumaco", I34],
  ["coumacp", I34],
  ["caffac", I34],
  ["chlrac", I34],
  ["ferac", I34],
  ["apigen", I34],
  ["apigen6cgls", I34],
  ["apigen7onshps", I34],
  ["luteol", I34],
  ["kaemf", I34],
  ["querce", I34],
  ["querce3bdgls", I34],
  ["querce3ortns", I34],
  ["querce3bgls", I34],
  ["isormt", I34],
  ["myrct", I34],
  ["rsvrtol", I34],
  ["hespt", I34],
  ["narng", I34],
  ["hespd", I34],
  ["daidzn", I34],
  ["gnstein", I34],
  ["epicatec", I34],
  ["epicategc", I34],
  ["epicatgc3gal", I34],
  ["catec", I34],
  ["galcatecgal", I34],
  ["galcatec", I34],
  ["syrgac", I34],
  ["sinpac", I34],
  ["ellgac", I34],
  ["polyph", I34],
  ["rafs", I23],
  ["stas", I23],
  ["vers", I23],
  ["ajgs", I23],
  ["camt", I33],
  ["stgstr", I33],
  ["stostrb", I33],
  ["phytac", I35],
  ["sapon", I36],
  ["vitb", null],
  ["vitd", I19],
  ["vitk", I20],
  ["tocph", I16],
  ["toctr", I16],
  ["amiace", I32],
  ["amiacce", I32],
  ["amiacne", I32],
  ["amiac", I32],
  ["orgac", I29],
  ["fauns", I31],
  ["faess", I31],
  ["facn3", I31],
  ["facn6", I31],
  ["facn9", I31],
  ["famscis", I31],
  ["fatrn", I31],
  ["olsac", I23],
  ["phystr", I33],
  ["mnrleq", null],
  ["mnrlet", null],
  ["mnrlpet", null],
  ["mnrlnet", null],
  ["mnrltx", null],
  ["carot", I18],
  ["xantp", I18],
  ["cartbeq", I18],
  ["vita", I17],
  ["vit", null],
]);
module.exports = CORPUS;
