var CORPUS = new Map([
  ["code", {parents:"",ancestry:"",children:"name grup regn"}],
  ["name", {parents:"code",ancestry:"code",children:"scie lang"}],
  ["scie", {parents:"name",ancestry:"name code",children:""}],
  ["lang", {parents:"name",ancestry:"name code",children:""}],
  ["grup", {parents:"code",ancestry:"code",children:""}],
  ["regn", {parents:"code",ancestry:"code",children:""}],
  ["water", {parents:"",ancestry:"",children:""}],
  ["protcnt", {parents:"",ancestry:"",children:""}],
  ["ash", {parents:"",ancestry:"",children:"mnrleq mnrlet mnrlpet mnrlnet mnrltx"}],
  ["fatce", {parents:"",ancestry:"",children:"fasat fauns faess"}],
  ["fibtg", {parents:"",ancestry:"",children:"fibins fibsol"}],
  ["fibins", {parents:"fibtg",ancestry:"fibtg",children:""}],
  ["fibsol", {parents:"fibtg",ancestry:"fibtg",children:""}],
  ["choavldf", {parents:"",ancestry:"",children:"cho"}],
  ["enerc", {parents:"",ancestry:"",children:""}],
  ["thia", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["ribf", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["nia", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["pantac", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["vitb6c", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["biot", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["folsum", {parents:"vitb",ancestry:"vitb vit",children:""}],
  ["vitc", {parents:"vit",ancestry:"vit",children:""}],
  ["retol", {parents:"vita",ancestry:"vita vit",children:""}],
  ["ergcal", {parents:"vitd",ancestry:"vitd vit",children:""}],
  ["chocal", {parents:"vitd",ancestry:"vitd vit",children:""}],
  ["doh25", {parents:"vitd",ancestry:"vitd vit",children:""}],
  ["tocpha", {parents:"tocph",ancestry:"tocph",children:""}],
  ["tocphb", {parents:"tocph",ancestry:"tocph",children:""}],
  ["tocphg", {parents:"tocph",ancestry:"tocph",children:""}],
  ["tocphd", {parents:"tocph",ancestry:"tocph",children:""}],
  ["toctra", {parents:"toctr",ancestry:"toctr",children:""}],
  ["toctrb", {parents:"toctr",ancestry:"toctr",children:""}],
  ["toctrg", {parents:"toctr",ancestry:"toctr",children:""}],
  ["toctrd", {parents:"toctr",ancestry:"toctr",children:""}],
  ["vite", {parents:"vit",ancestry:"vit",children:""}],
  ["vitk1", {parents:"vitk",ancestry:"vitk vit",children:""}],
  ["vitk2", {parents:"vitk",ancestry:"vitk vit",children:""}],
  ["lutn", {parents:"xantp",ancestry:"xantp cartoid",children:""}],
  ["zea", {parents:"xantp",ancestry:"xantp cartoid",children:""}],
  ["crypxb", {parents:"xantp",ancestry:"xantp cartoid",children:""}],
  ["lycpn", {parents:"carot",ancestry:"carot cartoid",children:""}],
  ["cartg", {parents:"carot",ancestry:"carot cartoid",children:""}],
  ["carta", {parents:"carot",ancestry:"carot cartoid",children:""}],
  ["cartb", {parents:"carot",ancestry:"carot cartoid",children:""}],
  ["cartoid", {parents:"",ancestry:"",children:"carot xantp"}],
  ["al", {parents:"mnrlnet",ancestry:"mnrlnet ash",children:""}],
  ["as", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["cd", {parents:"mnrlnet",ancestry:"mnrlnet ash",children:""}],
  ["ca", {parents:"mnrleq",ancestry:"mnrleq ash",children:""}],
  ["cr", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["co", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["cu", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["fe", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["pb", {parents:"mnrlnet",ancestry:"mnrlnet ash",children:""}],
  ["li", {parents:"mnrlpet",ancestry:"mnrlpet ash",children:""}],
  ["mg", {parents:"mnrleq",ancestry:"mnrleq ash",children:""}],
  ["mn", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["hg", {parents:"mnrltx",ancestry:"mnrltx ash",children:""}],
  ["mo", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["ni", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["p", {parents:"mnrleq",ancestry:"mnrleq ash",children:""}],
  ["k", {parents:"mnrleq",ancestry:"mnrleq ash",children:""}],
  ["se", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["na", {parents:"mnrleq",ancestry:"mnrleq ash",children:""}],
  ["zn", {parents:"mnrlet",ancestry:"mnrlet ash",children:""}],
  ["cho", {parents:"choavldf",ancestry:"choavldf",children:"starch fsugar olsac"}],
  ["starch", {parents:"cho",ancestry:"cho choavldf",children:""}],
  ["frus", {parents:"fsugar",ancestry:"fsugar cho choavldf",children:""}],
  ["glus", {parents:"fsugar",ancestry:"fsugar cho choavldf",children:""}],
  ["sucs", {parents:"fsugar",ancestry:"fsugar cho choavldf",children:""}],
  ["mals", {parents:"fsugar",ancestry:"fsugar cho choavldf",children:""}],
  ["fsugar", {parents:"cho",ancestry:"cho choavldf",children:"frus glus sucs mals lactose"}],
  ["lactose", {parents:"fsugar",ancestry:"fsugar cho choavldf",children:""}],
  ["f4d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f6d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f8d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f10d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f11d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f12d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f14d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f15d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f16d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f18d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f20d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f22d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f24d0", {parents:"fasat",ancestry:"fasat fatce",children:""}],
  ["f14d1cn5", {parents:"famscis",ancestry:"famscis fams fauns fatce",children:""}],
  ["f16d1cn7", {parents:"famscis",ancestry:"famscis fams fauns fatce",children:""}],
  ["f18d1cn9", {parents:"facn9 famscis",ancestry:"facn9 famscis fams fauns fatce",children:""}],
  ["f18d1tn9", {parents:"fatrn",ancestry:"fatrn fams fauns fatce",children:""}],
  ["f20d1cn9", {parents:"facn9 famscis",ancestry:"facn9 famscis fams fauns fatce",children:""}],
  ["f22d1cn9", {parents:"facn9 famscis",ancestry:"facn9 famscis fams fauns fatce",children:""}],
  ["f24d1cn9", {parents:"facn9 famscis",ancestry:"facn9 famscis fams fauns fatce",children:""}],
  ["f18d2cn6", {parents:"facn6 faess fapu",ancestry:"facn6 faess fatce fapu fauns",children:""}],
  ["f20d2n6", {parents:"facn6 fapu",ancestry:"facn6 fapu fauns fatce",children:""}],
  ["f22d2n6", {parents:"facn6 fapu",ancestry:"facn6 fapu fauns fatce",children:""}],
  ["f18d3n3", {parents:"facn3 faess fapu",ancestry:"facn3 faess fatce fapu fauns",children:""}],
  ["f20d3n6", {parents:"facn6 fapu",ancestry:"facn6 fapu fauns fatce",children:""}],
  ["f20d4n6", {parents:"facn6 faess fapu",ancestry:"facn6 faess fatce fapu fauns",children:""}],
  ["f20d5n3", {parents:"facn3 faess fapu",ancestry:"facn3 faess fatce fapu fauns",children:""}],
  ["f22d5n3", {parents:"facn3 fapu",ancestry:"facn3 fapu fauns fatce",children:""}],
  ["f22d6n3", {parents:"facn3 faess fapu",ancestry:"facn3 faess fatce fapu fauns",children:""}],
  ["fasat", {parents:"fatce",ancestry:"fatce",children:"f4d0 f6d0 f8d0 f10d0 f11d0 f12d0 f14d0 f15d0 f16d0 f18d0 f20d0 f22d0 f24d0"}],
  ["fams", {parents:"fauns",ancestry:"fauns fatce",children:"famscis fatrn"}],
  ["fapu", {parents:"fauns",ancestry:"fauns fatce",children:"f18d2cn6 f20d2n6 f22d2n6 f18d3n3 f20d3n6 f20d4n6 f20d5n3 f22d5n3 f22d6n3"}],
  ["cholc", {parents:"",ancestry:"",children:""}],
  ["his", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["ile", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["leu", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["lys", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["met", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["cys", {parents:"amiacce",ancestry:"amiacce amiac",children:""}],
  ["phe", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["thr", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["trp", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["val", {parents:"amiace",ancestry:"amiace amiac",children:""}],
  ["ala", {parents:"amiacne",ancestry:"amiacne amiac",children:""}],
  ["arg", {parents:"amiacce",ancestry:"amiacce amiac",children:""}],
  ["asp", {parents:"amiacne",ancestry:"amiacne amiac",children:""}],
  ["glu", {parents:"amiacne",ancestry:"amiacne amiac",children:""}],
  ["gly", {parents:"amiacce",ancestry:"amiacce amiac",children:""}],
  ["pro", {parents:"amiacce",ancestry:"amiacce amiac",children:""}],
  ["ser", {parents:"amiacne",ancestry:"amiacne amiac",children:""}],
  ["tyr", {parents:"amiacce",ancestry:"amiacce amiac",children:""}],
  ["oxalt", {parents:"orgac",ancestry:"orgac",children:"oxals oxali"}],
  ["oxals", {parents:"oxalt",ancestry:"oxalt orgac",children:""}],
  ["oxali", {parents:"oxalt",ancestry:"oxalt orgac",children:""}],
  ["caconac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["citac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["fumac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["malac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["quinac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["sucac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["tarac", {parents:"orgac",ancestry:"orgac",children:""}],
  ["dhbenzac34", {parents:"polyph",ancestry:"polyph",children:""}],
  ["hbenzal3", {parents:"polyph",ancestry:"polyph",children:""}],
  ["pcathac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["vanlac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["gallac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["cinmac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["coumaco", {parents:"polyph",ancestry:"polyph",children:""}],
  ["coumacp", {parents:"polyph",ancestry:"polyph",children:""}],
  ["caffac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["chlrac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["ferac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["apigen", {parents:"polyph",ancestry:"polyph",children:""}],
  ["apigen6cgls", {parents:"polyph",ancestry:"polyph",children:""}],
  ["apigen7onshps", {parents:"polyph",ancestry:"polyph",children:""}],
  ["luteol", {parents:"polyph",ancestry:"polyph",children:""}],
  ["kaemf", {parents:"polyph",ancestry:"polyph",children:""}],
  ["querce", {parents:"polyph",ancestry:"polyph",children:""}],
  ["querce3bdgls", {parents:"polyph",ancestry:"polyph",children:""}],
  ["querce3ortns", {parents:"polyph",ancestry:"polyph",children:""}],
  ["querce3bgls", {parents:"polyph",ancestry:"polyph",children:""}],
  ["isormt", {parents:"polyph",ancestry:"polyph",children:""}],
  ["myrct", {parents:"polyph",ancestry:"polyph",children:""}],
  ["rsvrtol", {parents:"polyph",ancestry:"polyph",children:""}],
  ["hespt", {parents:"polyph",ancestry:"polyph",children:""}],
  ["narng", {parents:"polyph",ancestry:"polyph",children:""}],
  ["hespd", {parents:"polyph",ancestry:"polyph",children:""}],
  ["daidzn", {parents:"polyph",ancestry:"polyph",children:""}],
  ["gnstein", {parents:"polyph",ancestry:"polyph",children:""}],
  ["epicatec", {parents:"polyph",ancestry:"polyph",children:""}],
  ["epicategc", {parents:"polyph",ancestry:"polyph",children:""}],
  ["epicatgc3gal", {parents:"polyph",ancestry:"polyph",children:""}],
  ["catec", {parents:"polyph",ancestry:"polyph",children:""}],
  ["galcatecgal", {parents:"polyph",ancestry:"polyph",children:""}],
  ["galcatec", {parents:"polyph",ancestry:"polyph",children:""}],
  ["syrgac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["sinpac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["ellgac", {parents:"polyph",ancestry:"polyph",children:""}],
  ["polyph", {parents:"",ancestry:"",children:"dhbenzac34 hbenzal3 pcathac vanlac gallac cinmac coumaco coumacp caffac chlrac ferac apigen apigen6cgls apigen7onshps luteol kaemf querce querce3bdgls querce3ortns querce3bgls isormt myrct rsvrtol hespt narng hespd daidzn gnstein epicatec epicategc epicatgc3gal catec galcatecgal galcatec syrgac sinpac ellgac"}],
  ["rafs", {parents:"olsac",ancestry:"olsac cho choavldf",children:""}],
  ["stas", {parents:"olsac",ancestry:"olsac cho choavldf",children:""}],
  ["vers", {parents:"olsac",ancestry:"olsac cho choavldf",children:""}],
  ["ajgs", {parents:"olsac",ancestry:"olsac cho choavldf",children:""}],
  ["camt", {parents:"phystr",ancestry:"phystr",children:""}],
  ["stgstr", {parents:"phystr",ancestry:"phystr",children:""}],
  ["stostrb", {parents:"phystr",ancestry:"phystr",children:""}],
  ["phytac", {parents:"",ancestry:"",children:""}],
  ["sapon", {parents:"",ancestry:"",children:""}],
  ["vitb", {parents:"vit",ancestry:"vit",children:"thia ribf nia pantac vitb6c biot folsum"}],
  ["vitd", {parents:"vit",ancestry:"vit",children:"ergcal chocal doh25"}],
  ["vitk", {parents:"vit",ancestry:"vit",children:"vitk1 vitk2"}],
  ["tocph", {parents:"",ancestry:"",children:"tocpha tocphb tocphg tocphd"}],
  ["toctr", {parents:"",ancestry:"",children:"toctra toctrb toctrg toctrd"}],
  ["amiace", {parents:"amiac",ancestry:"amiac",children:"his ile leu lys met phe thr trp val"}],
  ["amiacce", {parents:"amiac",ancestry:"amiac",children:"cys arg gly pro tyr"}],
  ["amiacne", {parents:"amiac",ancestry:"amiac",children:"ala asp glu ser"}],
  ["amiac", {parents:"",ancestry:"",children:"amiace amiacce amiacne"}],
  ["orgac", {parents:"",ancestry:"",children:"oxalt caconac citac fumac malac quinac sucac tarac"}],
  ["fauns", {parents:"fatce",ancestry:"fatce",children:"fams fapu"}],
  ["faess", {parents:"fatce",ancestry:"fatce",children:"f18d2cn6 f18d3n3 f20d4n6 f20d5n3 f22d6n3"}],
  ["facn3", {parents:"",ancestry:"",children:"f18d3n3 f20d5n3 f22d5n3 f22d6n3"}],
  ["facn6", {parents:"",ancestry:"",children:"f18d2cn6 f20d2n6 f22d2n6 f20d3n6 f20d4n6"}],
  ["facn9", {parents:"",ancestry:"",children:"f18d1cn9 f20d1cn9 f22d1cn9 f24d1cn9"}],
  ["famscis", {parents:"fams",ancestry:"fams fauns fatce",children:"f14d1cn5 f16d1cn7 f18d1cn9 f20d1cn9 f22d1cn9 f24d1cn9"}],
  ["fatrn", {parents:"fams",ancestry:"fams fauns fatce",children:"f18d1tn9"}],
  ["olsac", {parents:"cho",ancestry:"cho choavldf",children:"rafs stas vers ajgs"}],
  ["phystr", {parents:"",ancestry:"",children:"camt stgstr stostrb"}],
  ["mnrleq", {parents:"ash",ancestry:"ash",children:"ca mg p k na"}],
  ["mnrlet", {parents:"ash",ancestry:"ash",children:"as cr co cu fe mn mo ni se zn"}],
  ["mnrlpet", {parents:"ash",ancestry:"ash",children:"li"}],
  ["mnrlnet", {parents:"ash",ancestry:"ash",children:"al cd pb"}],
  ["mnrltx", {parents:"ash",ancestry:"ash",children:"hg"}],
  ["carot", {parents:"cartoid",ancestry:"cartoid",children:"lycpn cartg carta cartb"}],
  ["xantp", {parents:"cartoid",ancestry:"cartoid",children:"lutn zea crypxb"}],
  ["cartbeq", {parents:"vita",ancestry:"vita vit",children:""}],
  ["vita", {parents:"vit",ancestry:"vit",children:"retol cartbeq"}],
  ["vit", {parents:"",ancestry:"",children:"vitc vite vitb vitd vitk vita"}],
]);
module.exports = CORPUS;
