var CORPUS = new Map([
  ["code", {code:"code",parents:"",ancestry:"",children:"name grup regn"}],
  ["name", {code:"name",parents:"code",ancestry:"code",children:"scie lang"}],
  ["scie", {code:"scie",parents:"name",ancestry:"code",children:""}],
  ["lang", {code:"lang",parents:"name",ancestry:"code",children:""}],
  ["grup", {code:"grup",parents:"code",ancestry:"code",children:""}],
  ["regn", {code:"regn",parents:"code",ancestry:"code",children:""}],
  ["water", {code:"water",parents:"",ancestry:"",children:""}],
  ["protcnt", {code:"protcnt",parents:"",ancestry:"",children:""}],
  ["ash", {code:"ash",parents:"",ancestry:"",children:"mnrleq mnrlet mnrlpet mnrlnet mnrltx"}],
  ["fatce", {code:"fatce",parents:"",ancestry:"",children:"fasat fauns faess"}],
  ["fibtg", {code:"fibtg",parents:"",ancestry:"",children:"fibins fibsol"}],
  ["fibins", {code:"fibins",parents:"fibtg",ancestry:"fibtg",children:""}],
  ["fibsol", {code:"fibsol",parents:"fibtg",ancestry:"fibtg",children:""}],
  ["choavldf", {code:"choavldf",parents:"",ancestry:"",children:"cho"}],
  ["enerc", {code:"enerc",parents:"",ancestry:"",children:""}],
  ["thia", {code:"thia",parents:"vitb",ancestry:"vit",children:""}],
  ["ribf", {code:"ribf",parents:"vitb",ancestry:"vit",children:""}],
  ["nia", {code:"nia",parents:"vitb",ancestry:"vit",children:""}],
  ["pantac", {code:"pantac",parents:"vitb",ancestry:"vit",children:""}],
  ["vitb6c", {code:"vitb6c",parents:"vitb",ancestry:"vit",children:""}],
  ["biot", {code:"biot",parents:"vitb",ancestry:"vit",children:""}],
  ["folsum", {code:"folsum",parents:"vitb",ancestry:"vit",children:""}],
  ["vitc", {code:"vitc",parents:"vit",ancestry:"vit",children:""}],
  ["retol", {code:"retol",parents:"vita",ancestry:"vit",children:""}],
  ["ergcal", {code:"ergcal",parents:"vitd",ancestry:"vit",children:""}],
  ["chocal", {code:"chocal",parents:"vitd",ancestry:"vit",children:""}],
  ["doh25", {code:"doh25",parents:"vitd",ancestry:"vit",children:""}],
  ["tocpha", {code:"tocpha",parents:"tocph",ancestry:"tocph",children:""}],
  ["tocphb", {code:"tocphb",parents:"tocph",ancestry:"tocph",children:""}],
  ["tocphg", {code:"tocphg",parents:"tocph",ancestry:"tocph",children:""}],
  ["tocphd", {code:"tocphd",parents:"tocph",ancestry:"tocph",children:""}],
  ["toctra", {code:"toctra",parents:"toctr",ancestry:"toctr",children:""}],
  ["toctrb", {code:"toctrb",parents:"toctr",ancestry:"toctr",children:""}],
  ["toctrg", {code:"toctrg",parents:"toctr",ancestry:"toctr",children:""}],
  ["toctrd", {code:"toctrd",parents:"toctr",ancestry:"toctr",children:""}],
  ["vite", {code:"vite",parents:"vit",ancestry:"vit",children:""}],
  ["vitk1", {code:"vitk1",parents:"vitk",ancestry:"vit",children:""}],
  ["vitk2", {code:"vitk2",parents:"vitk",ancestry:"vit",children:""}],
  ["lutn", {code:"lutn",parents:"xantp",ancestry:"cartoid",children:""}],
  ["zea", {code:"zea",parents:"xantp",ancestry:"cartoid",children:""}],
  ["crypxb", {code:"crypxb",parents:"xantp",ancestry:"cartoid",children:""}],
  ["lycpn", {code:"lycpn",parents:"carot",ancestry:"cartoid",children:""}],
  ["cartg", {code:"cartg",parents:"carot",ancestry:"cartoid",children:""}],
  ["carta", {code:"carta",parents:"carot",ancestry:"cartoid",children:""}],
  ["cartb", {code:"cartb",parents:"carot",ancestry:"cartoid",children:""}],
  ["cartoid", {code:"cartoid",parents:"",ancestry:"",children:"carot xantp"}],
  ["al", {code:"al",parents:"mnrlnet",ancestry:"ash",children:""}],
  ["as", {code:"as",parents:"mnrlet",ancestry:"ash",children:""}],
  ["cd", {code:"cd",parents:"mnrlnet",ancestry:"ash",children:""}],
  ["ca", {code:"ca",parents:"mnrleq",ancestry:"ash",children:""}],
  ["cr", {code:"cr",parents:"mnrlet",ancestry:"ash",children:""}],
  ["co", {code:"co",parents:"mnrlet",ancestry:"ash",children:""}],
  ["cu", {code:"cu",parents:"mnrlet",ancestry:"ash",children:""}],
  ["fe", {code:"fe",parents:"mnrlet",ancestry:"ash",children:""}],
  ["pb", {code:"pb",parents:"mnrlnet",ancestry:"ash",children:""}],
  ["li", {code:"li",parents:"mnrlpet",ancestry:"ash",children:""}],
  ["mg", {code:"mg",parents:"mnrleq",ancestry:"ash",children:""}],
  ["mn", {code:"mn",parents:"mnrlet",ancestry:"ash",children:""}],
  ["hg", {code:"hg",parents:"mnrltx",ancestry:"ash",children:""}],
  ["mo", {code:"mo",parents:"mnrlet",ancestry:"ash",children:""}],
  ["ni", {code:"ni",parents:"mnrlet",ancestry:"ash",children:""}],
  ["p", {code:"p",parents:"mnrleq",ancestry:"ash",children:""}],
  ["k", {code:"k",parents:"mnrleq",ancestry:"ash",children:""}],
  ["se", {code:"se",parents:"mnrlet",ancestry:"ash",children:""}],
  ["na", {code:"na",parents:"mnrleq",ancestry:"ash",children:""}],
  ["zn", {code:"zn",parents:"mnrlet",ancestry:"ash",children:""}],
  ["cho", {code:"cho",parents:"choavldf",ancestry:"choavldf",children:"starch fsugar olsac"}],
  ["starch", {code:"starch",parents:"cho",ancestry:"choavldf",children:""}],
  ["frus", {code:"frus",parents:"fsugar",ancestry:"choavldf",children:""}],
  ["glus", {code:"glus",parents:"fsugar",ancestry:"choavldf",children:""}],
  ["sucs", {code:"sucs",parents:"fsugar",ancestry:"choavldf",children:""}],
  ["mals", {code:"mals",parents:"fsugar",ancestry:"choavldf",children:""}],
  ["fsugar", {code:"fsugar",parents:"cho",ancestry:"choavldf",children:"frus glus sucs mals lactose"}],
  ["lactose", {code:"lactose",parents:"fsugar",ancestry:"choavldf",children:""}],
  ["f4d0", {code:"f4d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f6d0", {code:"f6d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f8d0", {code:"f8d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f10d0", {code:"f10d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f11d0", {code:"f11d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f12d0", {code:"f12d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f14d0", {code:"f14d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f15d0", {code:"f15d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f16d0", {code:"f16d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f18d0", {code:"f18d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f20d0", {code:"f20d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f22d0", {code:"f22d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f24d0", {code:"f24d0",parents:"fasat",ancestry:"fatce",children:""}],
  ["f14d1cn5", {code:"f14d1cn5",parents:"famscis",ancestry:"fatce",children:""}],
  ["f16d1cn7", {code:"f16d1cn7",parents:"famscis",ancestry:"fatce",children:""}],
  ["f18d1cn9", {code:"f18d1cn9",parents:"facn9 famscis",ancestry:"facn9 fatce",children:""}],
  ["f18d1tn9", {code:"f18d1tn9",parents:"fatrn",ancestry:"fatce",children:""}],
  ["f20d1cn9", {code:"f20d1cn9",parents:"facn9 famscis",ancestry:"facn9 fatce",children:""}],
  ["f22d1cn9", {code:"f22d1cn9",parents:"facn9 famscis",ancestry:"facn9 fatce",children:""}],
  ["f24d1cn9", {code:"f24d1cn9",parents:"facn9 famscis",ancestry:"facn9 fatce",children:""}],
  ["f18d2cn6", {code:"f18d2cn6",parents:"facn6 faess fapu",ancestry:"facn6 fatce",children:""}],
  ["f20d2n6", {code:"f20d2n6",parents:"facn6 fapu",ancestry:"facn6 fatce",children:""}],
  ["f22d2n6", {code:"f22d2n6",parents:"facn6 fapu",ancestry:"facn6 fatce",children:""}],
  ["f18d3n3", {code:"f18d3n3",parents:"facn3 faess fapu",ancestry:"facn3 fatce",children:""}],
  ["f20d3n6", {code:"f20d3n6",parents:"facn6 fapu",ancestry:"facn6 fatce",children:""}],
  ["f20d4n6", {code:"f20d4n6",parents:"facn6 faess fapu",ancestry:"facn6 fatce",children:""}],
  ["f20d5n3", {code:"f20d5n3",parents:"facn3 faess fapu",ancestry:"facn3 fatce",children:""}],
  ["f22d5n3", {code:"f22d5n3",parents:"facn3 fapu",ancestry:"facn3 fatce",children:""}],
  ["f22d6n3", {code:"f22d6n3",parents:"facn3 faess fapu",ancestry:"facn3 fatce",children:""}],
  ["fasat", {code:"fasat",parents:"fatce",ancestry:"fatce",children:"f4d0 f6d0 f8d0 f10d0 f11d0 f12d0 f14d0 f15d0 f16d0 f18d0 f20d0 f22d0 f24d0"}],
  ["fams", {code:"fams",parents:"fauns",ancestry:"fatce",children:"famscis fatrn"}],
  ["fapu", {code:"fapu",parents:"fauns",ancestry:"fatce",children:"f18d2cn6 f20d2n6 f22d2n6 f18d3n3 f20d3n6 f20d4n6 f20d5n3 f22d5n3 f22d6n3"}],
  ["cholc", {code:"cholc",parents:"",ancestry:"",children:""}],
  ["his", {code:"his",parents:"amiace",ancestry:"amiac",children:""}],
  ["ile", {code:"ile",parents:"amiace",ancestry:"amiac",children:""}],
  ["leu", {code:"leu",parents:"amiace",ancestry:"amiac",children:""}],
  ["lys", {code:"lys",parents:"amiace",ancestry:"amiac",children:""}],
  ["met", {code:"met",parents:"amiace",ancestry:"amiac",children:""}],
  ["cys", {code:"cys",parents:"amiacce",ancestry:"amiac",children:""}],
  ["phe", {code:"phe",parents:"amiace",ancestry:"amiac",children:""}],
  ["thr", {code:"thr",parents:"amiace",ancestry:"amiac",children:""}],
  ["trp", {code:"trp",parents:"amiace",ancestry:"amiac",children:""}],
  ["val", {code:"val",parents:"amiace",ancestry:"amiac",children:""}],
  ["ala", {code:"ala",parents:"amiacne",ancestry:"amiac",children:""}],
  ["arg", {code:"arg",parents:"amiacce",ancestry:"amiac",children:""}],
  ["asp", {code:"asp",parents:"amiacne",ancestry:"amiac",children:""}],
  ["glu", {code:"glu",parents:"amiacne",ancestry:"amiac",children:""}],
  ["gly", {code:"gly",parents:"amiacce",ancestry:"amiac",children:""}],
  ["pro", {code:"pro",parents:"amiacce",ancestry:"amiac",children:""}],
  ["ser", {code:"ser",parents:"amiacne",ancestry:"amiac",children:""}],
  ["tyr", {code:"tyr",parents:"amiacce",ancestry:"amiac",children:""}],
  ["oxalt", {code:"oxalt",parents:"orgac",ancestry:"orgac",children:"oxals oxali"}],
  ["oxals", {code:"oxals",parents:"oxalt",ancestry:"orgac",children:""}],
  ["oxali", {code:"oxali",parents:"oxalt",ancestry:"orgac",children:""}],
  ["caconac", {code:"caconac",parents:"orgac",ancestry:"orgac",children:""}],
  ["citac", {code:"citac",parents:"orgac",ancestry:"orgac",children:""}],
  ["fumac", {code:"fumac",parents:"orgac",ancestry:"orgac",children:""}],
  ["malac", {code:"malac",parents:"orgac",ancestry:"orgac",children:""}],
  ["quinac", {code:"quinac",parents:"orgac",ancestry:"orgac",children:""}],
  ["sucac", {code:"sucac",parents:"orgac",ancestry:"orgac",children:""}],
  ["tarac", {code:"tarac",parents:"orgac",ancestry:"orgac",children:""}],
  ["dhbenzac34", {code:"dhbenzac34",parents:"polyph",ancestry:"polyph",children:""}],
  ["hbenzal3", {code:"hbenzal3",parents:"polyph",ancestry:"polyph",children:""}],
  ["pcathac", {code:"pcathac",parents:"polyph",ancestry:"polyph",children:""}],
  ["vanlac", {code:"vanlac",parents:"polyph",ancestry:"polyph",children:""}],
  ["gallac", {code:"gallac",parents:"polyph",ancestry:"polyph",children:""}],
  ["cinmac", {code:"cinmac",parents:"polyph",ancestry:"polyph",children:""}],
  ["coumaco", {code:"coumaco",parents:"polyph",ancestry:"polyph",children:""}],
  ["coumacp", {code:"coumacp",parents:"polyph",ancestry:"polyph",children:""}],
  ["caffac", {code:"caffac",parents:"polyph",ancestry:"polyph",children:""}],
  ["chlrac", {code:"chlrac",parents:"polyph",ancestry:"polyph",children:""}],
  ["ferac", {code:"ferac",parents:"polyph",ancestry:"polyph",children:""}],
  ["apigen", {code:"apigen",parents:"polyph",ancestry:"polyph",children:""}],
  ["apigen6cgls", {code:"apigen6cgls",parents:"polyph",ancestry:"polyph",children:""}],
  ["apigen7onshps", {code:"apigen7onshps",parents:"polyph",ancestry:"polyph",children:""}],
  ["luteol", {code:"luteol",parents:"polyph",ancestry:"polyph",children:""}],
  ["kaemf", {code:"kaemf",parents:"polyph",ancestry:"polyph",children:""}],
  ["querce", {code:"querce",parents:"polyph",ancestry:"polyph",children:""}],
  ["querce3bdgls", {code:"querce3bdgls",parents:"polyph",ancestry:"polyph",children:""}],
  ["querce3ortns", {code:"querce3ortns",parents:"polyph",ancestry:"polyph",children:""}],
  ["querce3bgls", {code:"querce3bgls",parents:"polyph",ancestry:"polyph",children:""}],
  ["isormt", {code:"isormt",parents:"polyph",ancestry:"polyph",children:""}],
  ["myrct", {code:"myrct",parents:"polyph",ancestry:"polyph",children:""}],
  ["rsvrtol", {code:"rsvrtol",parents:"polyph",ancestry:"polyph",children:""}],
  ["hespt", {code:"hespt",parents:"polyph",ancestry:"polyph",children:""}],
  ["narng", {code:"narng",parents:"polyph",ancestry:"polyph",children:""}],
  ["hespd", {code:"hespd",parents:"polyph",ancestry:"polyph",children:""}],
  ["daidzn", {code:"daidzn",parents:"polyph",ancestry:"polyph",children:""}],
  ["gnstein", {code:"gnstein",parents:"polyph",ancestry:"polyph",children:""}],
  ["epicatec", {code:"epicatec",parents:"polyph",ancestry:"polyph",children:""}],
  ["epicategc", {code:"epicategc",parents:"polyph",ancestry:"polyph",children:""}],
  ["epicatgc3gal", {code:"epicatgc3gal",parents:"polyph",ancestry:"polyph",children:""}],
  ["catec", {code:"catec",parents:"polyph",ancestry:"polyph",children:""}],
  ["galcatecgal", {code:"galcatecgal",parents:"polyph",ancestry:"polyph",children:""}],
  ["galcatec", {code:"galcatec",parents:"polyph",ancestry:"polyph",children:""}],
  ["syrgac", {code:"syrgac",parents:"polyph",ancestry:"polyph",children:""}],
  ["sinpac", {code:"sinpac",parents:"polyph",ancestry:"polyph",children:""}],
  ["ellgac", {code:"ellgac",parents:"polyph",ancestry:"polyph",children:""}],
  ["polyph", {code:"polyph",parents:"",ancestry:"",children:"dhbenzac34 hbenzal3 pcathac vanlac gallac cinmac coumaco coumacp caffac chlrac ferac apigen apigen6cgls apigen7onshps luteol kaemf querce querce3bdgls querce3ortns querce3bgls isormt myrct rsvrtol hespt narng hespd daidzn gnstein epicatec epicategc epicatgc3gal catec galcatecgal galcatec syrgac sinpac ellgac"}],
  ["rafs", {code:"rafs",parents:"olsac",ancestry:"choavldf",children:""}],
  ["stas", {code:"stas",parents:"olsac",ancestry:"choavldf",children:""}],
  ["vers", {code:"vers",parents:"olsac",ancestry:"choavldf",children:""}],
  ["ajgs", {code:"ajgs",parents:"olsac",ancestry:"choavldf",children:""}],
  ["camt", {code:"camt",parents:"phystr",ancestry:"phystr",children:""}],
  ["stgstr", {code:"stgstr",parents:"phystr",ancestry:"phystr",children:""}],
  ["stostrb", {code:"stostrb",parents:"phystr",ancestry:"phystr",children:""}],
  ["phytac", {code:"phytac",parents:"",ancestry:"",children:""}],
  ["sapon", {code:"sapon",parents:"",ancestry:"",children:""}],
  ["vitb", {code:"vitb",parents:"vit",ancestry:"vit",children:"thia ribf nia pantac vitb6c biot folsum"}],
  ["vitd", {code:"vitd",parents:"vit",ancestry:"vit",children:"ergcal chocal doh25"}],
  ["vitk", {code:"vitk",parents:"vit",ancestry:"vit",children:"vitk1 vitk2"}],
  ["tocph", {code:"tocph",parents:"",ancestry:"",children:"tocpha tocphb tocphg tocphd"}],
  ["toctr", {code:"toctr",parents:"",ancestry:"",children:"toctra toctrb toctrg toctrd"}],
  ["amiace", {code:"amiace",parents:"amiac",ancestry:"amiac",children:"his ile leu lys met phe thr trp val"}],
  ["amiacce", {code:"amiacce",parents:"amiac",ancestry:"amiac",children:"cys arg gly pro tyr"}],
  ["amiacne", {code:"amiacne",parents:"amiac",ancestry:"amiac",children:"ala asp glu ser"}],
  ["amiac", {code:"amiac",parents:"",ancestry:"",children:"amiace amiacce amiacne"}],
  ["orgac", {code:"orgac",parents:"",ancestry:"",children:"oxalt caconac citac fumac malac quinac sucac tarac"}],
  ["fauns", {code:"fauns",parents:"fatce",ancestry:"fatce",children:"fams fapu"}],
  ["faess", {code:"faess",parents:"fatce",ancestry:"fatce",children:"f18d2cn6 f18d3n3 f20d4n6 f20d5n3 f22d6n3"}],
  ["facn3", {code:"facn3",parents:"",ancestry:"",children:"f18d3n3 f20d5n3 f22d5n3 f22d6n3"}],
  ["facn6", {code:"facn6",parents:"",ancestry:"",children:"f18d2cn6 f20d2n6 f22d2n6 f20d3n6 f20d4n6"}],
  ["facn9", {code:"facn9",parents:"",ancestry:"",children:"f18d1cn9 f20d1cn9 f22d1cn9 f24d1cn9"}],
  ["famscis", {code:"famscis",parents:"fams",ancestry:"fatce",children:"f14d1cn5 f16d1cn7 f18d1cn9 f20d1cn9 f22d1cn9 f24d1cn9"}],
  ["fatrn", {code:"fatrn",parents:"fams",ancestry:"fatce",children:"f18d1tn9"}],
  ["olsac", {code:"olsac",parents:"cho",ancestry:"choavldf",children:"rafs stas vers ajgs"}],
  ["phystr", {code:"phystr",parents:"",ancestry:"",children:"camt stgstr stostrb"}],
  ["mnrleq", {code:"mnrleq",parents:"ash",ancestry:"ash",children:"ca mg p k na"}],
  ["mnrlet", {code:"mnrlet",parents:"ash",ancestry:"ash",children:"as cr co cu fe mn mo ni se zn"}],
  ["mnrlpet", {code:"mnrlpet",parents:"ash",ancestry:"ash",children:"li"}],
  ["mnrlnet", {code:"mnrlnet",parents:"ash",ancestry:"ash",children:"al cd pb"}],
  ["mnrltx", {code:"mnrltx",parents:"ash",ancestry:"ash",children:"hg"}],
  ["carot", {code:"carot",parents:"cartoid",ancestry:"cartoid",children:"lycpn cartg carta cartb"}],
  ["xantp", {code:"xantp",parents:"cartoid",ancestry:"cartoid",children:"lutn zea crypxb"}],
  ["cartbeq", {code:"cartbeq",parents:"vita",ancestry:"vit",children:""}],
  ["vita", {code:"vita",parents:"vit",ancestry:"vit",children:"retol cartbeq"}],
  ["vit", {code:"vit",parents:"",ancestry:"",children:"vitc vite vitb vitd vitk vita"}],
]);
module.exports = CORPUS;
